export const refs = {
  searchInput: document.querySelector('.js-search-control'),
  linkMyLibrary: document.querySelector('.js-lib_page'),
  linkHome: document.querySelector('.js-home_page'),
  logoHome: document.querySelector('.js-logo'),
  watchedLibrary: document.querySelector('.js-btn_watched'),
  queueLibrary: document.querySelector('.js-btn_queue'),
  aboutTeam: document.querySelector('.js-link-footer'),
  galleryList: document.querySelector('.js-gallery-list'),
  btnScrollUP: document.querySelector('.js-buttonScrollUp'),
  spinnerPreloader: document.querySelector('.js-preloader-page'),
  modalBtnRemoveWatched: document.querySelector('.js-modal-btn-remove-watched'),
  modalBtnWatched: document.querySelector('.js-modal-btn-watched'),
  modalBtnQueue: document.querySelector('.js-modal-btn-queue'),
  modalBtnRemoveQueue: document.querySelector('.js-modal-btn-remove-queue'),
  modalBackdrop: document.querySelector('.js-backdrop'),
  modalCloseBtn: document.querySelector('.js-close-btn'),
  modal: document.querySelector('.js-modal'),
  searchForm: document.querySelector('.js-search-form'),
};
