import './js/headerMenu.js';
import './js/spinner.js';
import './sass/main.scss';
import './js/fetchAPI.js';
import './js/localStorageAPI.js';
import './js/buttonScrollUp.js';
// import './js/modal-movie-render.js';
import './js/infiniteScroll.js';
import './js/modalClose.js';
import './js/onCardClick.js';
import './js/renderFromLocalStorage.js';
import './js/eventHandlerSearch.js';